# Generated by Django 6.0.3 on 2026-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('Computing', 'Computing'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('Humanities', 'Humanities & Sciences')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.CharField(default='SLIIT', max_length=255),
        ),
    ]
