# Generated by Django 6.0.3 on 2026-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_faculty_user_full_name_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_proficiency',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('NATIVE', 'Native/Fluent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TUTOR', 'Tutor'), ('STUDENT_TUTOR', 'Student Tutor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=15),
        ),
    ]
