# Generated by Django 6.0.3 on 2026-04-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_target_proficiency_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_tutor_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_proof',
            field=models.ImageField(blank=True, null=True, upload_to='verification/student_ids/'),
        ),
        migrations.CreateModel(
            name='StudentTutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_areas', models.JSONField(default=list)),
                ('bio', models.TextField(help_text='Short teaching bio or motivation')),
                ('availability', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
