# Generated by Django 6.0.3 on 2026-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_agreed_to_tutor_terms_user_identity_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_pre_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
