# Generated by Django 6.0.3 on 2026-04-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_email_pre_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttutorprofile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='verification/tutor_videos/'),
        ),
    ]
