# Generated by Django 6.0.3 on 2026-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tutorotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
