# Generated by Django 6.0.3 on 2026-04-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_course_chapter_enrollment_lesson_lessoncompletion_and_more'),
        ('api', '0008_studenttutorprofile_hourly_rate'),
    ]

    operations = [
    ]
