# Generated by Django 6.0.3 on 2026-04-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_quiz_models'),
        ('api', '0010_wallquestion_wallanswer'),
    ]

    operations = [
    ]
