# Generated by Django 6.0.3 on 2026-04-10 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260410_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonauthoringprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-pk']},
        ),
        migrations.RemoveIndex(
            model_name='lessonquizattempt',
            name='api_lessonq_enrollm_ee080b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonquizattempt',
            name='api_lessonq_quiz_id_8819d9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lessonquizattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wallquestion',
            name='votes',
        ),
        migrations.AddField(
            model_name='wallquestion',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
