# Generated by Django 6.0.3 on 2026-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_lessonauthoringprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('GRAMMAR', 'Grammar'), ('VOCABULARY', 'Vocabulary'), ('WRITING', 'Writing'), ('IELTS', 'ielts')], max_length=20),
        ),
    ]
