# Generated by Django 6.0.3 on 2026-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_in_bank',
            field=models.BooleanField(default=False, help_text='Whether this question is added to the shared question bank'),
        ),
    ]
