# Generated by Django 6.0.3 on 2026-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_is_in_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this question is approved by admin for use in daily quiz'),
        ),
    ]
