# Generated by Django 6.0.3 on 2026-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='learning_link',
            field=models.URLField(blank=True, help_text='Learning resource URL for incorrect answers', null=True),
        ),
    ]
