# Generated by Django 6.0.3 on 2026-04-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification'),
        ('api', '0017_quizquestion_learning_link'),
        ('api', '0018_course_approval_notes_course_approval_status_and_more'),
    ]

    operations = [
    ]
